### ISSUE TITLE
Sink does not support custom properties/enrichers.

### ISSUE THREAD

**Issue by hzhengran** [Cimpress-MCP/serilog-sinks-awscloudwatch#37] opened 2017-05-27 06:21 UTC
All information form enriches and custom properties is lost when writing to cloud watch log.

**Comment by wparad** [comment] 2017-05-27 08:22
@hzhengran, would you be able to provide your configuration for reproduction?

**Comment by hzhengran** [comment] 2017-05-27 08:50
### Setup logger:
```
        static void SetupLogging()
        {
            var config = new LoggerConfiguration()
                .ReadFrom.AppSettings()                
                .Enrich.With<ThreadIdEnricher>()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("Source", new
                {
                    Name = "MyWorkerName",
                    Type = "Worker"
                }, true);

            Log.Logger = config.CreateLogger();
        }    
```

And I'm using following config in app.config file:

```
  <appSettings>
    <!-- Add AwsCloudWatchSink to Serilog Config -->
    <add key="serilog:using:AmazonCloudWatch" value="Serilog.Sinks.AwsCloudWatch"/>
    <add key="serilog:write-to:AmazonCloudWatch.logGroupName" value="Test"/>
    <add key="serilog:write-to:AmazonCloudWatch.logStreamNamePrefix" value="MyWorkerLog"/>
    <add key="serilog:write-to:AmazonCloudWatch.accessKey" value="***"/>
    <add key="serilog:write-to:AmazonCloudWatch.secretAccessKey" value="***"/>
    <add key="serilog:write-to:AmazonCloudWatch.regionName" value="us-east-1"/>
  </appSettings>
```

### Caller:
`Log.Fatal(ex, "Some message template");`

### Expected result:
Get full information including `ThreadId` and `CustomProperties`. Like:
```
{
    "Timestamp": "2017-05-27T16:23:20.4070264+08:00",
    "Level": 5,
    "MessageTemplate": {
        "Text": "Some message template???",
        "Tokens": [
            {
                "Length": 24,
                "Text": "Some message template",
                "StartIndex": 0
            }
        ]
    },
    "Properties": {
        "ThreadId": {
            "Value": 5
        },
        "Source": {
            "TypeTag": null,
            "Properties": [
                {
                    "Name": "Name",
                    "Value": {
                        "Value": "Worker"
                    }
                },
                {
                    "Name": "Type",
                    "Value": {
                        "Value": "Worker"
                    }
                }
            ]
        }
    },
    "Exception": {
        "ClassName": "System.ArgumentNullException",
        "Message": "Something should not be null.",
        "Data": null,
        "InnerException": null,
        "HelpURL": null,
        "StackTraceString": "   at Program.cs:line 39",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": "8\n Timer_Elapsed(System.Object, System.Timers.ElapsedEventArgs)",
        "HResult": -2147467261,
        "Source": "CloudWatchTestV2",
        "WatsonBuckets": null,
        "ParamName": "SSaS"
    }
}
```

### Actual result:
A plain text `Some message template`.

**Comment by wparad** [comment] 2017-05-27 13:33
@hzhengran, would you be able to help explain why #38 resolves the issue you are seeing here.  We'll look into the configuration to see if something was missed, but it isn't immediately clear why the implementation solves the problem above.  Thanks for the additional information.

**Comment by hzhengran** [comment] 2017-05-31 01:23
As talked in #32, config via appsettings is the only approach for me to use this sink. However, i cannot create and pass a `ILogEventRenderer` through config file since it only accepts `string` values. Moreover, the default renderer is losing information which doesn't seem to make sense to me. So I add a JSON serializer to convert the `exception` into JSON to keep all information.

**Comment by wparad** [comment] 2017-05-31 07:13
I agree that the properties not being displayed an the missing exception information are problematic.  Updating the default renderer to include that information would solve this issue.

If the information can't be passed to the library via the config for serilog, please make a bug report on the main library, this isn't the place to solve that problem.

**Comment by RomanBorysenok** [comment] 2017-06-20 13:14
Hello,

I have the same issue described below.
I want to add CorrelationId to all my logs. I created a middleware that pushing CorrelationId

**Comment by RomanBorysenok** [comment] 2017-06-20 14:30
@thoean thanks for the quick reply!
It works for me, maybe you could add this example to the README?
Because it's not quite clear.
Thanks ones again!

**Comment by thoean** [comment] 2017-06-21 07:41
Excellent idea. I've created a wiki page to get started: https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/wiki/Using-a-JSON-renderer.

With that, I'm closing this issue.

**Closed by thoean** 2017-06-21 07:41 UTC
