### ISSUE TITLE
Serilog.Sinks.AwsCloudWatch does not work with MAUI Blazor Apps

### ISSUE THREAD

**Issue by genifycom** [Cimpress-MCP/serilog-sinks-awscloudwatch#109] opened 2022-10-18 19:27 UTC
The current Serilog.Sinks.AwsCloudWatch targets .NET Standard 2.0 and I have used it extensively with Xamarin Forms BlazorHybrid apps.

Under Maui, we cannot get this to work. I have tried both platform independent and platform dependent code (in either Windows or Android).

The code compiles and runs but does not produce an AWS log or log messages.

Sample setup:

              .WriteTo.AmazonCloudWatch(
                    logGroup: "myawslog", // The name of the log group to log to
                    logStreamPrefix: DateTime.UtcNow.ToString("yyyyMMddHHmmssfff"), // A string that our log stream names should be prefixed with. We are just specifying the start timestamp as the log stream prefix
                    batchSizeLimit: 100, // (Optional) Maximum number of log events that should be sent in a batch to AWS CloudWatch
                    queueSizeLimit: 10000, // (Optional) The maximum number of log messages that are stored locally before being sentto AWS Cloudwatch
                    batchUploadPeriodInSeconds: 15, // (Optional) Similar to above, except the maximum amount of time that should pass before log events must be sent to AWS CloudWatch
                    createLogGroup: true, // (Optional) If the log group does not exists, should we try create it?
                    maxRetryAttempts: 3, // (Optional) The number of attempts we should make when logging log events that fail                       
                    logGroupRetentionPolicy: LogGroupRetentionPolicy.OneWeek, // (Optional) Specify the time that logs should be kept for in AWS CloudWatch
                    cloudWatchClient: client) // The AWS CloudWatch client to use

**Comment by genifycom** [comment] 2022-10-18 19:49
Anyone know a workaround?

**Comment by wparad** [comment] 2022-10-18 21:33
We'll be able to investigate as soon as we have a minimal reproduction that provides it isn't working. We look forwarding to see that. Thank you.

**Comment by genifycom** [comment] 2022-10-19 00:51
[MauiApp2.zip](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/files/9815899/MauiApp2.zip)

**Comment by wparad** [comment] 2022-10-19 00:58
@genifycom there's a ton of files in there which makes it really difficult for us, can you reduce that to a minimal reproduction that causes the problem?

Perhaps I should explain what I mean by a **minimal reproduction**: _The least amount of code that exists that demonstrates the problem_. This likely should be your `app.config`, a `program.cs`, and a `logger.log` statement. Additionally due to the type of problem, your IAM role configuration as well as your log group/stream configuration will also be necessary to validate this.

Thanks!

**Comment by genifycom** [comment] 2022-10-19 17:20
The method I used was to create a default Maui blazor app in VS 2022, version 17.6.3

Only MauiProgram.cs was altered from the default app.

I added the one method SetUpSerilog() on line 36 which sets up the AmazonCloudWatch and logs one message on line 59.

Lines 11 and 12 are the key and secret key.

If I copy and paste this SetUpSerilog() to a ASP.NET Core Web App, then this method works fine (i.e. my AWS side is the same).

[MauiProgram.zip](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/files/9822804/MauiProgram.zip)

MauiProgram.cs is included here. Just replace the one created by the default app to test.

**Comment by wparad** [comment] 2022-10-20 12:33
Just so I understand, you are saying with this code:

```c#
using Amazon.CloudWatchLogs;
using MauiApp2.Data;
using Microsoft.AspNetCore.Components.WebView.Maui;
using Serilog;
using Serilog.Sinks.AwsCloudWatch;

namespace MauiApp2
{
    public static class MauiProgram
    {
        public const string aws_access_key = "AKIAXXXXXXXXXXXXXXX";
        public const string aws_secret_key = "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY";

        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            builder.Services.AddMauiBlazorWebView();
#if DEBUG
            builder.Services.AddBlazorWebViewDeveloperTools();
#endif

            builder.Services.AddSingleton<WeatherForecastService>();

            SetUpSerilog();

            return builder.Build();
        }

        public static void SetUpSerilog()
        {
            // setup AWS CloudWatch client use RegionEndpoint.USWest1 or RegionEndpoint.GetBySystemName(aws_region)
            var client = new AmazonCloudWatchLogsClient(aws_access_key, aws_secret_key, Amazon.RegionEndpoint.USWest1);

            // Attach the sink to the logger configuration
            //https://blog.ivankahl.com/logging-dotnet-to-aws-cloudwatch-using-serilog/
            //https://stackoverflow.com/questions/59676018/how-to-configure-serilog-logging-to-cloudwatch-using-json
            Log.Logger = new LoggerConfiguration()
              .Enrich.FromLogContext() //https://github.com/serilog/serilog/wiki/Enrichment
              .MinimumLevel.Information()
              .WriteTo.AmazonCloudWatch(
                    logGroup: "testmauiapp", // The name of the log group to log to
                    logStreamPrefix: DateTime.UtcNow.ToString("yyyyMMddHHmmssfff"), // A string that our log stream names should be prefixed with. We are just specifying the start timestamp as the log stream prefix
                    batchSizeLimit: 100, //// (Optional) Maximum number of log events that should be sent in a batch to AWS CloudWatch
                    queueSizeLimit: 10000, // (Optional) The maximum number of log messages that are stored locally before being sentto AWS Cloudwatch
                    batchUploadPeriodInSeconds: 15, // (Optional) Similar to above, except the maximum amount of time that should pass before log events must be sent to AWS CloudWatch
                    createLogGroup: true, // (Optional) If the log group does not exists, should we try to create it?
                    maxRetryAttempts: 3, // (Optional) The number of attempts we should make when logging log events that fail                       
                    logGroupRetentionPolicy: LogGroupRetentionPolicy.OneWeek, // (Optional) Specify the time that logs should be kept for in AWS CloudWatch
                    cloudWatchClient: client) // The AWS CloudWatch client to use
              .CreateLogger();

            Log.Information("Logger created");
        }
    }
}
```

It logs correctly to cloudwatch if you comment out everything from the `public static MauiApp CreateMauiApp` method, but when uncommented it doesn't log the `Logger Created` message?

**Comment by wparad** [comment] 2022-11-07 09:33
Closing for lack of reproduction, currently provided code works.

**Closed by wparad** 2022-11-07 09:33 UTC
